default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: db

development:
  <<: *default
  database: payment_app_development

test:
  <<: *default
  database: payment_app_test

production:
  <<: *default
  database: payment_app_production
  username: payment_app
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
